#:import AnchorLayout kivy.uix.anchorlayout
#:import StackLayout kivy.uix.stacklayout
#:import GridLayout kivy.uix.gridlayout

<SampGridLayout>:
	rows: 2
	BoxLayout:
		size_hint_y: None
		height: 30
		spacing: 10
		canvas: 
			Color:
				rgba: 1, 1, 1, 1
			Rectangle:
				pos: self.pos
				size: self.size
		Button
			background_normal: 'open.png'
			background_down: 'open.png'
			size_hint_x: 0.5
            size_hint_y: 0.5
			width: 30
		Button
			background_normal: 'money.png'
			background_down: 'money.png'
			size_hint_x: 0.5
            size_hint_y: 0.5
			width: 30
		Button
			background_normal: 'home.png'
			background_down: 'home.png'
			size_hint_x: 0.5
            size_hint_y: 0.5
			width: 30
