#:import Toolbar kivymd.toolbar.Toolbar
#:import ThemeManager kivymd.theming.ThemeManager
#:import MDNavigationDrawer_HeaderStringOnly kivymd.navigationdrawer.MDNavigationDrawer_HeaderStringOnly
#:import NavigationLayout kivymd.navigationdrawer.NavigationLayout
#:import NavigationDrawerDivider kivymd.navigationdrawer.NavigationDrawerDivider
#:import NavigationDrawerToolbar kivymd.navigationdrawer.NavigationDrawerToolbar
#:import NavigationDrawerSubheader kivymd.navigationdrawer.NavigationDrawerSubheader
#:import MDCheckbox kivymd.selectioncontrols.MDCheckbox
#:import MDSwitch kivymd.selectioncontrols.MDSwitch
#:import MDList kivymd.list.MDList
#:import OneLineListItem kivymd.list.OneLineListItem
#:import TwoLineListItem kivymd.list.TwoLineListItem
#:import ThreeLineListItem kivymd.list.ThreeLineListItem
#:import OneLineAvatarListItem kivymd.list.OneLineAvatarListItem
#:import OneLineIconListItem kivymd.list.OneLineIconListItem
#:import OneLineAvatarIconListItem kivymd.list.OneLineAvatarIconListItem
#:import MDTextField kivymd.textfields.MDTextField
#:import MDSpinner kivymd.spinner.MDSpinner
#:import MDCard kivymd.card.MDCard
#:import MDSeparator kivymd.card.MDSeparator
#:import MDDropdownMenu kivymd.menu.MDDropdownMenu
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import colors kivymd.color_definitions.colors
#:import SmartTile kivymd.grid.SmartTile
#:import MDSlider kivymd.slider.MDSlider
#:import MDTabbedPanel kivymd.tabs.MDTabbedPanel
#:import MDTab kivymd.tabs.MDTab
#:import MDProgressBar kivymd.progressbar.MDProgressBar
#:import MDAccordion kivymd.accordion.MDAccordion
#:import MDAccordionItem kivymd.accordion.MDAccordionItem
#:import MDAccordionSubItem kivymd.accordion.MDAccordionSubItem
#:import MDThemePicker kivymd.theme_picker.MDThemePicker
#:import MDBottomNavigation kivymd.tabs.MDBottomNavigation
#:import MDBottomNavigationItem kivymd.tabs.MDBottomNavigationItem
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import AnchorLayout kivy.uix.anchorlayout
#:import StackLayout kivy.uix.stacklayout
#:import GridLayout kivy.uix.gridlayout
#:import Window kivy.core.window.Window
NavigationLayout:
    id: nav_layout
    MDNavigationDrawer_HeaderStringOnly:
        id: nav_drawer
        header_name: 'Authors Name'
        subheader_name: 'Authors Job Position'
        NavigationDrawerDivider:
        NavigationDrawerSubheader:
            text: "Authors Menu"
        NavigationDrawerIconButton:
            icon: 'view-dashboard'
            text: "Dashboard"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_Dashboard'
        NavigationDrawerIconButton:
            icon: 'view-list'
            text: "Data Management"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_SimplifiedView'
        NavigationDrawerDivider:
        NavigationDrawerSubheader:
            text: "Account"
        NavigationDrawerIconButton:
            icon: 'face'
            text: "Add Author"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountAddInfo'
        NavigationDrawerIconButton:
            icon: 'delete-sweep'
            text: "Remove Author"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountDeleteInfo'
        NavigationDrawerIconButton:
            icon: 'key-change'
            text: "Edit Author Info"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountEditInfo'
        NavigationDrawerIconButton:
            icon: 'nature-people'
            text: "Change Author"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountUserSelection'
        NavigationDrawerIconButton:
            id: ToolMenu_6
            icon: 'exit-to-app'
            text: "Exit Application"
            #on_release: root.MDButton_Trigger_ExitConfirm()#app.get_running_app().stop()
    BoxLayout:
        orientation: 'vertical'
        Toolbar:
            id: ToolbarMain
            title: app.title
            md_bg_color: get_color_from_hex(colors[app.theme_cls.primary_palette][app.theme_cls.primary_hue])
            background_palette: app.theme_cls.primary_palette
            background_hue: app.theme_cls.primary_hue
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]
            #Add an If and else on this icon
            right_action_items: [['brightness-1', lambda x: app.MDButton_DarkMode()]]
            darkBooleanParameter: False
        ScreenManager:
            id: ScreenFrame_MainWindow
            transition: FadeTransition(clearcolor=[255, 255, 255, 0])
            Screen:
                name: 'Startup_FirstTime_GetInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                        # size: self.texture_size[0] / 2, self.texture_size[1] / 2
                        # opacity: 0.1
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Hello and Welcome!'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'Please set the following... This wont take a while...'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    hint_text: "Input Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Password"
                                    required: True
                                    helper_text: "Password is needed to avoid changing authors without permission."
                                    helper_text_mode: "on_focus"
                                    password: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                    on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_SimplifiedView'
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                    on_release: app.MDToolbar_DynamicContent_Change('ThisIsATest', 'Red', '' ,'')
            Screen:
                name: 'MainWindow_Dashboard'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                    ScrollView:
                        do_scroll_x: False                            
                        GridLayout:
                            cols:2 if Window.width < 1200 else 2
                            size_hint_y: None
                            spacing: dp(10)
                            padding: dp(10)
                            height: self.minimum_height
                            MDCard:
                            # I just realized that removing size_hint will make the card resizable
                                size: dp(320), dp(180)
                                size_hint_y: None
                                padding: dp(15)
                                StackLayout:
                                    spacing: dp(10)
                                    BoxLayout:
                                        orientation: 'horizontal'
                                        padding: dp(10)
                                        spacing: dp(10)
                                        MDLabel:
                                            font_style: 'Title'
                                            theme_text_color: 'Primary'
                                            halign: 'left'
                                            text: "Quick Actions"
                                            width: dp(10)
                                        MDRaisedButton:
                                            text: "Increment"
                                            size_hint_y: None
                                            size: 3 * dp(48), dp(48)
                                        MDRaisedButton:
                                            text: "Decrement"
                                            size_hint_y: None
                                            size: 3 * dp(48), dp(48)
                                        MDRaisedButton:
                                            text: "Remove Data"
                                            size_hint_y: None
                                            size: 3 * dp(48), dp(48)
                            MDCard:
                                size_hint: None, None
                                size: dp(320), dp(200)
                                BoxLayout:
                                    orientation:'vertical'
                                    padding: dp(10)
                                    MDLabel:
                                        text: 'Title'
                                        theme_text_color: 'Secondary'
                                        font_style: "Title"
                                        size_hint_y: None
                                    MDTextField:
                                        hint_text: "No helper text"
                                        write_tab: False
                                    MDTextField:
                                        hint_text: "Helper text on focus"
                                        helper_text: "This will disappear when you click off"
                                        helper_text_mode: "on_focus"
                                        write_tab: False
                                    MDTextField:
                                        hint_text: "Persistent helper text"
                                        helper_text: "Text is always here"
                                        helper_text_mode: "persistent"
                                        write_tab: False
            Screen:
                name: 'MainWindow_SimplifiedView'
                MDBottomNavigation:
                    id: MainFrameWindow_Divider
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_1'
                        text: "Data Binding and Setups"
                        icon: "database-plus"
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_2'
                        text: "Data Management"
                        icon: "view-list"
                        MDLabel:
                            font_style: 'Body1'
                            theme_text_color: 'Primary'
                            text: "Data List"
                            halign: 'center'
                        MDTabbedPanel:
                            id: tab_panel
                            tab_display_mode:'text'
                            tab_width_mode:'stacked'
                            MDTab:
                                name: 'Tab_IterateWorkheet#1'
                                text: "Tab_IterateWorkheet#1"
                                GridLayout:
                                    cols:2
                                    BoxLayout:
                                        orientation: 'vertical'
                                        ScrollView:
                                            do_scroll_x: False
                                            MDList:
                                                id: MDList_UserInsertion_Selection
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                                TwoLineAvatarListItem:
                                                    type: "two-line"
                                                    text: "Two-line item..."
                                                    secondary_text: "with avatar"
                                                    AvatarSampleWidget:
                                                        source: './assets/avatar.png'
                                    ScrollView:
                                        do_scroll_x: False                            
                                        GridLayout:
                                            cols:1
                                            size_hint_y: None
                                            spacing: dp(10)
                                            padding: dp(10)
                                            height: self.minimum_height
                                            MDCard:
                                            # I just realized that removing size_hint will make the card resizable
                                                size: dp(320), dp(180)
                                                size_hint_y: None
                                                padding: dp(15)
                                                BoxLayout:
                                                    orientation:'vertical'
                                                    MDLabel:
                                                        font_style: 'Headline'
                                                        theme_text_color: 'Primary'
                                                        text: "Quick Actions"
                                                        width: dp(20)
                                                        text_size: self.size
                                                        halign: 'left'
                                                        valign: 'top'
                                                    BoxLayout:
                                                        orientation: 'horizontal'
                                                        spacing: dp(10)
                                                        padding: 0
                                                        StackLayout:
                                                            spacing: dp(5)
                                                            MDRaisedButton:
                                                                text: "Increment Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                                            MDRaisedButton:
                                                                text: "Decrement Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                                            MDRaisedButton:
                                                                text: "Submit Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                                            MDRaisedButton:
                                                                text: "Increment Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                                            MDRaisedButton:
                                                                text: "Decrement Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                                            MDRaisedButton:
                                                                text: "Submit Data"
                                                                size_hint: None, None
                                                                size: 3 * dp(48), dp(48)
                                            MDCard:
                                            # I just realized that removing size_hint will make the card resizable
                                                size: dp(320), dp(130)
                                                size_hint_y: None
                                                padding: dp(15)
                                                elevation: 1
                                                BoxLayout:
                                                    orientation:'vertical'
                                                    MDLabel:
                                                        font_style: 'Headline'
                                                        theme_text_color: 'Primary'
                                                        text: "File Options"
                                                        width: dp(20)
                                                        text_size: self.size
                                                        halign: 'left'
                                                        valign: 'top'
                                                    BoxLayout:
                                                        orientation: 'horizontal'
                                                        spacing: dp(10)
                                                        padding: 0
                                                        MDRaisedButton:
                                                            text: "Save"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                                        MDRaisedButton:
                                                            text: "Reload Data"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                                        MDRaisedButton:
                                                            text: "Submit Data"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                            MDCard:
                                                size_hint_y: None
                                                size: dp(320), dp(880)
                                                padding: dp(15)
                                                BoxLayout:
                                                    orientation:'vertical'
                                                    spacing: dp(10)
                                                    MDLabel:
                                                        font_style: 'Headline'
                                                        theme_text_color: 'Primary'
                                                        text: "Data Editor"
                                                        width: dp(20)
                                                        text_size: self.size
                                                        halign: 'left'
                                                        valign: 'top'
                                                    MDTextField:
                                                        hint_text: "Item Number Input"
                                                        required: True
                                                        helper_mode: 'on_focus'
                                                        helper_text: 'Item Number of the Particular. Required...'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Particulars Input"
                                                        helper_text: 'Particular Name. Required...'
                                                        required: True
                                                        helper_mode: 'on_focus'
                                                        helper_text: ''
                                                        write_tab: False
                                                        MDFlatButton:
                                                            theme_text_color: 'Custom'
                                                            text: "Admin Previledge"
                                                            size_hint: None, None
                                                    MDTextField:
                                                        hint_text: "On Hand Value Input"
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Proposed Value Input"
                                                        helper_text: "Text is always here"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Unit Type Input"
                                                        helper_text: "Type of the Unit of the Particular"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Unit Value Input"
                                                        helper_text: "Text is always here"
                                                        helper_text_mode: "persistent"
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Total Value"
                                                        helper_text: "This value is automatically computed..."
                                                        helper_text_mode: "persistent"
                                                        write_tab: False
                                                        disabled: True
                                                    MDTextField:
                                                        hint_text: "Quarter #1 Value"
                                                        helper_text: "Quarter What Usage????????"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Quarter #2 Value"
                                                        helper_text: "Quarter What Usage????????"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Quarter #3 Value"
                                                        helper_text: "Quarter What Usage????????"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    MDTextField:
                                                        hint_text: "Quarter #4 Value"
                                                        helper_text: "Quarter What Usage????????"
                                                        helper_text_mode: 'on_focus'
                                                        write_tab: False
                                                    BoxLayout:
                                                        orientation: 'horizontal'
                                                        spacing: dp(10)
                                                        MDRaisedButton:
                                                            text: "Apply"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                                        MDFlatButton:
                                                            text: "Clear Input"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                                        MDFlatButton:
                                                            text: "Increment"
                                                            size_hint: None, None
                                                            size: 3 * dp(48), dp(48)
                                            #MDCard:
                                            #    size: dp(320), dp(280)
                                            #    size_hint_y: None
                                            #    padding: dp(15)
                                            #    BoxLayout:
                                            #        orientation: 'vertical'
                                            #        padding: 0, dp(20)
                                            #        MDLabel:
                                            #            orientation: 'vertical'
                                            #            text: 'Data Editor'
                                            #            theme_text_color: 'Primary'
                                            #            font_style: "Headline"
                                            #            size_hint_y: None
                                            #        MDTextField:
                                            #            hint_text: "No helper text"
                                            #            size_hint_y: None
                                            #            write_tab: False
                                            #        MDTextField:
                                            #            hint_text: "Helper text on focus"
                                            #            size_hint_y: None
                                            #            helper_text: "This will disappear when you click off"
                                            #            helper_text_mode: "on_focus"
                                            #            write_tab: False
                                            #        MDTextField:
                                            #            hint_text: "Persistent helper text"
                                            #            size_hint_y: None
                                            #            helper_text: "Text is always here"
                                            #            helper_text_mode: "persistent"
                                            #            write_tab: False
                                            #        MDRaisedButton:
                                            #            text: "Apply"
                                            #            size_hint: None, None
                                            #            size: 3 * dp(48), dp(48)
                                            #        MDFlatButton:
                                            #            theme_text_color: 'Custom'
                                            #            text: "Clear Input"
                                            #            size_hint: None, None
                                            #            size: 3 * dp(48), dp(48)
                            MDTab:
                                name: 'Tab_IterateWorkheet#2'
                                text: 'Tab_IterateWorkheet#2'
                                MDLabel:
                                    font_style: 'Body1'
                                    theme_text_color: 'Primary'
                                    text: "Iterate Data per Worksheet! Remember!"
                                    halign: 'center'
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_3'
                        text: "Data Status Report"
                        icon: 'book-open'
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: None
                            padding: dp(48)
                            spacing: 10
                            #1 Summation of Units, Show Proposed  and OnHand and OnStorage
                            #2 Most Used Item Recorded
                            #3 Due Dates
                            #4 Recently Added 
                            GridLayout:
                                cols: 2
                                rows: 3
                                size_hint_y: None
                                height: self.minimum_height
                                spacing: dp(10)
                                size_hint_y: None
                                MDCard:
                                    size_hint: None, None
                                    size: dp(320), dp(200)
                                    BoxLayout:
                                        orientation:'vertical'
                                        padding: dp(10)
                                        MDLabel:
                                            text: 'Title'
                                            theme_text_color: 'Secondary'
                                            font_style: "Title"
                                            size_hint_y: None
                                        MDTextField:
                                            hint_text: "No helper text"
                                            write_tab: False
                                        MDTextField:
                                            hint_text: "Helper text on focus"
                                            helper_text: "This will disappear when you click off"
                                            helper_text_mode: "on_focus"
                                            write_tab: False
                                        MDTextField:
                                            hint_text: "Persistent helper text"
                                            helper_text: "Text is always here"
                                            helper_text_mode: "persistent"
                                            write_tab: False
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_4'
                        text: "Data Import and Export"
                        icon: 'book-open'
                        ScrollView:
                            do_scroll_x: False                              
                            GridLayout:
                                cols:2 if Window.width < 1400 else 1
                                size_hint_y: None
                                spacing: dp(10)
                                padding: dp(20)
                                height: self.minimum_height
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Value Incrementing Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Quick Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Quick Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Quick Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Quick Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                MDCard:
                                # I just realized that removing size_hint will make the card resizable
                                    size: dp(320), dp(180)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation: 'vertical'
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            StackLayout:
                                                spacing:20
                                                BoxLayout:
                                                    orientation: 'horizontal'
                                                    padding: dp(20)
                                                    spacing: 20
                                                    MDLabel:
                                                        font_style: 'Title'
                                                        theme_text_color: 'Primary'
                                                        halign: 'left'
                                                        text: "Quick Actions"
                                                        width: dp(10)
                                                    MDRaisedButton:
                                                        text: "Increment"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Decrement"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                    MDRaisedButton:
                                                        text: "Remove Value"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
            Screen:
                name: 'MainWindow_AccountUserSelection'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: 0, dp(20)
                            StackLayout:
                                spacing:20
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: dp(20), 0
                                    spacing: 20
                                    MDLabel:
                                        text: 'Select an Registered Author'
                                        theme_text_color: 'Primary'
                                        font_style: "Headline"
                                        size_hint_y: None
                                        height: dp(15)
                                    MDLabel:
                                        text: 'Please choose your identity with your true identity!'
                                        theme_text_color: 'Secondary'
                                        font_style: "Body1"
                                        size_hint_y: None
                                        height: dp(3)
                                    ScrollView:
                                        do_scroll_x: False
                                        MDList:
                                            id: MDList_UserInsertion_Selection
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
            Screen:
                name: 'MainWindow_AccountAddInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Add an Author'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'More staffs? Add more authors!'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    hint_text: "Input Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Password"
                                    required: True
                                    helper_text: "Password is needed to avoid changing authors without permission."
                                    helper_text_mode: "on_focus"
                                    password: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
            Screen:
                name: 'MainWindow_AccountDeleteInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: 0, dp(20)
                            StackLayout:
                                spacing:20
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: dp(20), 0
                                    spacing: 20
                                    MDLabel:
                                        text: 'Remove an Registered Author'
                                        theme_text_color: 'Primary'
                                        font_style: "Headline"
                                        size_hint_y: None
                                        height: dp(15)
                                    MDLabel:
                                        text: 'This is the place to remove an authors right of modification and view.'
                                        theme_text_color: 'Secondary'
                                        font_style: "Body1"
                                        size_hint_y: None
                                        height: dp(3)
                                    ScrollView:
                                        do_scroll_x: False
                                        MDList:
                                            id: MDList_UserDeletion_Selection
                                            NavigationDrawerIconButton:
                                                icon: 'tab-unselected'
                                                text: "Unselect Checked Author"
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                    MDFlatButton:
                                        theme_text_color: 'Custom'
                                        text: "Remove Selected"
                                        size_hint: None, None
                                        size: 3 * dp(48), dp(48)
                                        pos_hint: {'center_y': 0.9}
            Screen:
                name: 'MainWindow_AccountEditInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Edit your Information'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'Type Mistake? Wrong Info? Correct That One Here!'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    hint_text: "Edit Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Password"
                                    required: True
                                    helper_text: "Password is needed to avoid changing authors without permission."
                                    helper_text_mode: "on_focus"
                                    password: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)