#:import Toolbar kivymd.toolbar.Toolbar
#:import ThemeManager kivymd.theming.ThemeManager
#:import MDNavigationDrawer kivymd.navigationdrawer.MDNavigationDrawer
#:import NavigationLayout kivymd.navigationdrawer.NavigationLayout
#:import NavigationDrawerDivider kivymd.navigationdrawer.NavigationDrawerDivider
#:import NavigationDrawerToolbar kivymd.navigationdrawer.NavigationDrawerToolbar
#:import NavigationDrawerSubheader kivymd.navigationdrawer.NavigationDrawerSubheader
#:import MDCheckbox kivymd.selectioncontrols.MDCheckbox
#:import MDSwitch kivymd.selectioncontrols.MDSwitch
#:import MDList kivymd.list.MDList
#:import OneLineListItem kivymd.list.OneLineListItem
#:import TwoLineListItem kivymd.list.TwoLineListItem
#:import ThreeLineListItem kivymd.list.ThreeLineListItem
#:import OneLineAvatarListItem kivymd.list.OneLineAvatarListItem
#:import OneLineIconListItem kivymd.list.OneLineIconListItem
#:import OneLineAvatarIconListItem kivymd.list.OneLineAvatarIconListItem
#:import MDTextField kivymd.textfields.MDTextField
#:import MDSpinner kivymd.spinner.MDSpinner
#:import MDCard kivymd.card.MDCard
#:import MDSeparator kivymd.card.MDSeparator
#:import MDDropdownMenu kivymd.menu.MDDropdownMenu
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import colors kivymd.color_definitions.colors
#:import SmartTile kivymd.grid.SmartTile
#:import MDSlider kivymd.slider.MDSlider
#:import MDTabbedPanel kivymd.tabs.MDTabbedPanel
#:import MDTab kivymd.tabs.MDTab
#:import MDProgressBar kivymd.progressbar.MDProgressBar
#:import MDAccordion kivymd.accordion.MDAccordion
#:import MDAccordionItem kivymd.accordion.MDAccordionItem
#:import MDAccordionSubItem kivymd.accordion.MDAccordionSubItem
#:import MDThemePicker kivymd.theme_picker.MDThemePicker
#:import MDBottomNavigation kivymd.tabs.MDBottomNavigation
#:import MDBottomNavigationItem kivymd.tabs.MDBottomNavigationItem
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import AnchorLayout kivy.uix.anchorlayout
NavigationLayout:
    id: nav_layout
    MDNavigationDrawer:
        id: nav_drawer
        NavigationDrawerToolbar:
            title: "Main Menu"
        NavigationDrawerSubheader:
            text: "Potential Breaking"
        NavigationDrawerIconButton:
            icon: 'view-dashboard'
            text: "Dashboard"
            on_release: app.root.ids.scr_mngr.current = 'Startup_FirstTime'
        NavigationDrawerIconButton:
            icon: 'database'
            text: "Data Station"
            on_release: app.root.ids.scr_mngr.current = 'Startup_FirstTime'
        NavigationDrawerIconButton:
            icon: 'checkbox-blank-circle'
            text: "Home"
            on_release: app.root.ids.scr_mngr.current = 'Startup_FirstTime'
        NavigationDrawerSubheader:
            text: "Accounts"
        NavigationDrawerIconButton:
            icon: 'face-profile'
            text: "Edit Profile"
            on_release: app.root.ids.scr_mngr.current = 'Startup_FirstTime'
        NavigationDrawerIconButton:
            icon: 'nature-people'
            text: "Change User"
            on_release: app.root.ids.scr_mngr.current = 'Startup_FirstTime'
        NavigationDrawerIconButton:
            icon: 'exit-to-app'
            text: "Exit Application"
            on_release: app.get_running_app().stop()
    BoxLayout:
        orientation: 'vertical'
        Toolbar:
            id: ToolbarMain
            title: app.title
            md_bg_color: get_color_from_hex(colors[app.theme_cls.primary_palette]['700'])
            background_palette: app.theme_cls.primary_palette
            background_hue: '700'
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]
            #right_action_items: [['dots-vertical', lambda x: app.root.toggle_nav_drawer()]]
        ScreenManager:
            id: scr_mngr
            transition: FadeTransition(clearcolor=[255, 255, 255, 0])
            Screen:
                name: 'Startup_FirstTime'
                MDCard:
                    size_hint: None, None
                    size: dp(520), dp(320)
                    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                    BoxLayout:
                        orientation: 'vertical'
                        padding: dp(15)
                        MDTextField:
                            id: text_field_error
                            hint_text: "Helper text on error (Hit Enter with two characters here)"
                            helper_text: "Two is my least favorite number"
                            helper_text_mode: "on_error"
                        MDTextField:
                            hint_text: "required = True"
                            required: True
                            helper_text_mode: "on_error"
                        MDTextField:
                            hint_text: "Max text length = 10"
                            max_text_length: 10
                            write_tab: False
                            #on_release: app.show_example_dialog()