#:import Toolbar kivymd.toolbar.Toolbar
#:import ThemeManager kivymd.theming.ThemeManager
#:import MDNavigationDrawer_HeaderStringOnly kivymd.navigationdrawer.MDNavigationDrawer_HeaderStringOnly
#:import NavigationLayout kivymd.navigationdrawer.NavigationLayout
#:import NavigationDrawerDivider kivymd.navigationdrawer.NavigationDrawerDivider
#:import NavigationDrawerToolbar kivymd.navigationdrawer.NavigationDrawerToolbar
#:import NavigationDrawerSubheader kivymd.navigationdrawer.NavigationDrawerSubheader
#:import MDCheckbox kivymd.selectioncontrols.MDCheckbox
#:import MDSwitch kivymd.selectioncontrols.MDSwitch
#:import MDList kivymd.list.MDList
#:import OneLineListItem kivymd.list.OneLineListItem
#:import TwoLineListItem kivymd.list.TwoLineListItem
#:import ThreeLineListItem kivymd.list.ThreeLineListItem
#:import OneLineAvatarListItem kivymd.list.OneLineAvatarListItem
#:import OneLineIconListItem kivymd.list.OneLineIconListItem
#:import OneLineAvatarIconListItem kivymd.list.OneLineAvatarIconListItem
#:import MDTextField kivymd.textfields.MDTextField
#:import MDSpinner kivymd.spinner.MDSpinner
#:import MDCard kivymd.card.MDCard
#:import MDSeparator kivymd.card.MDSeparator
#:import MDDropdownMenu kivymd.menu.MDDropdownMenu
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import colors kivymd.color_definitions.colors
#:import SmartTile kivymd.grid.SmartTile
#:import MDSlider kivymd.slider.MDSlider
#:import MDTabbedPanel kivymd.tabs.MDTabbedPanel
#:import MDTab kivymd.tabs.MDTab
#:import MDProgressBar kivymd.progressbar.MDProgressBar
#:import MDAccordion kivymd.accordion.MDAccordion
#:import MDAccordionItem kivymd.accordion.MDAccordionItem
#:import MDAccordionSubItem kivymd.accordion.MDAccordionSubItem
#:import MDThemePicker kivymd.theme_picker.MDThemePicker
#:import MDBottomNavigation kivymd.tabs.MDBottomNavigation
#:import MDBottomNavigationItem kivymd.tabs.MDBottomNavigationItem
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import AnchorLayout kivy.uix.anchorlayout
#:import StackLayout kivy.uix.stacklayout
#:import GridLayout kivy.uix.gridlayout
#:import Window kivy.core.window.Window
NavigationLayout:
    id: nav_layout
    MDNavigationDrawer_HeaderStringOnly:
        id: nav_drawer
        header_name: 'Hello, Authors Name!'
        subheader_name: 'Position: {Anything...}'
        NavigationDrawerDivider:
        NavigationDrawerSubheader:
            text: "Authors Menu"
        NavigationDrawerIconButton:
            icon: 'view-list'
            text: "Data Management"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_SimplifiedView'
        NavigationDrawerDivider:
        NavigationDrawerSubheader:
            text: "Account"
        NavigationDrawerIconButton:
            icon: 'face'
            text: "Add Author"
            #on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindo6w_AccountAddInfo'
            disabled: True
        NavigationDrawerIconButton:
            icon: 'delete-sweep'
            text: "Remove Author"
            #on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountDeleteInfo'
            disabled: True
        NavigationDrawerIconButton:
            icon: 'key-change'
            text: "Edit Author Info"
            on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountEditInfo'
        NavigationDrawerIconButton:
            icon: 'nature-people'
            text: "Change Author"
            #on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_AccountUserSelection'
            disabled: True
        NavigationDrawerIconButton:
            id: ToolMenu_6
            icon: 'exit-to-app'
            text: "Exit Application"
            #on_release: root.MDButton_Trigger_ExifadtConfirm()#app.get_running_app().stop()
    BoxLayout:
        orientation: 'vertical'
        Toolbar:
            id: ToolbarMain
            title: app.title
            md_bg_color: get_color_from_hex(colors[app.theme_cls.primary_palette][app.theme_cls.primary_hue])
            background_palette: app.theme_cls.primary_palette
            background_hue: app.theme_cls.primary_hue
            left_action_items: [['menu', lambda x: app.root.toggle_nav_drawer()]]
            #Add an If and else on this icon
            right_action_items: [['brightness-2', lambda x: app.MDButton_DarkMode()]]
            darkBooleanParameter: False
        ScreenManager:
            id: ScreenFrame_MainWindow
            transition: FadeTransition(clearcolor=[255, 255, 255, 0])
            Screen:
                name: 'Startup_FirstTime_GetInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                        # size: self.texture_size[0] / 2, self.texture_size[1] / 2
                        # opacity: 0.1
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Hello and Welcome!'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'Please set the following... This wont take a while...'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    id: FirstTimer_DataFirstName
                                    hint_text: "Input Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                    #text:  'What is this ghoosting in my keyboard!?!?!?'
                                MDTextField:
                                    id: FirstTimer_DataLastName
                                    hint_text: "Input Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    id: FirstTimer_DataJobPosition
                                    hint_text: "Input Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    id: FirstTimer_DataPassword
                                    hint_text: "Input Your Password"
                                    required: True
                                    helper_text: "Password is needed to avoid changing authors without permission."
                                    helper_text_mode: "on_focus"
                                    password: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    theme_text_color: 'Custom'
                                    size: 3 * dp(48), dp(48)
                                    #on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_SimplifiedView'
                                    #on_release: #app.ExcelLoadInit_Prototype()
                                    on_release: app.root.ids.ScreenFrame_MainWindow.current = 'MainWindow_SimplifiedView'        
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                    on_release: app.MDToolbar_DynamicContent_Change('ThisIsATest', 'Red', '' ,'')
            Screen:
                name: 'MainWindow_SimplifiedView'
                MDBottomNavigation:
                    id: MainFrameWindow_Divider
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_1'
                        text: "Data Management"
                        icon: "view-list"
                        GridLayout:
                            cols:2
                            BoxLayout:
                                orientation: 'vertical'
                                ScrollView:
                                    foon_reedo_scroll_x: False
                                    MDList:
                                        id: MDList_UserData_Insertion
                                        #Statically Add 100 List Item due to Issues. Please refer to ExcelLoadInit_Prototype() Funciton for more info. 
                                        TwoLineListItem:
                                            id: ListElement_1
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_2
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_3
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_4
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_5
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_6
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_7
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_8
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_9
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_10
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_11
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_12
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_13
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_14
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_15
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_16
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_17
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_18
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_19
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_20
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_21
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_22
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_23
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_24
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_25
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_26
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_27
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_28
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_29
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_30
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_31
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_32
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_33
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_34
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_35
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_36
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_37
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_38
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_39
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_40
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_41
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_42
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_43
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_44
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_45
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_46
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_47
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_48
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_49
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_50
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_51
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_52
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_53
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_54
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_55
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_56
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_57
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_58
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_59
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_60
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_61
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_62
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_63
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_64
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_65
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_66
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_67
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_68
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_69
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_70
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_71
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_72
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_73
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_74
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_75
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_76
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_77
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_78
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_79
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_80
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_81
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_82
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_83
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_84
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_85
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_86
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_87
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_88
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_89
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_90
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_91
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_92
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_93
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_94
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_95
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_96
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_97
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_98
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_99
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                                        TwoLineListItem:
                                            id: ListElement_100
                                            type: "two-line"
                                            text: "< No Particular / Description >"
                                            secondary_text: "{On Hand Val: Proposed Val: Unit Type: PerUnit Val, Q#1: Q#2: Q#3: Q#4:}"
                                            disabled: True
                            ScrollView:
                                do_scroll_x: False                            
                                GridLayout:
                                    cols:1
                                    size_hint_y: None
                                    spacing: dp(10)
                                    padding: dp(10)
                                    height: self.minimum_height
                                    MDCard:
                                        size_hint_y: None
                                        size: dp(320), dp(880)
                                        padding: dp(15)
                                        BoxLayout:
                                            orientation:'vertical'
                                            spacing: dp(10)
                                            MDLabel:
                                                font_style: 'Headline'
                                                theme_text_color: 'Primary'
                                                text: "Data Editor"
                                                width: dp(20)
                                                text_size: self.size
                                                halign: 'left'
                                                valign: 'top'
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Resource_ItemNumVal
                                                    hint_text: "Item Number Input"
                                                    helper_mode: 'on_focus'
                                                    helper_text: 'Item Number of the Particular. Required...'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            MDTextField:
                                                id: Resource_ParticularProperty
                                                hint_text: "Particulars Input"
                                                helper_text: 'Particular Name. Required...'
                                                helper_mode: 'on_focus'
                                                write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Admin Previledge"
                                                    size_hint: None, None
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Resource_OnHandVal
                                                    hint_text: "On Hand Value Input"
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Resource_ProposedVal
                                                    hint_text: "Proposed Value Input"
                                                    helper_text: "Text is always here"
                                                    helper_text_mode: 'on_focus'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            MDTextField:
                                                id: Resource_UnitTypeProperty
                                                hint_text: "Unit Type Input"
                                                helper_text: "Type of the Unit of the Particular"
                                                helper_text_mode: 'on_focus'
                                                write_tab: False
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Resource_UnitVal
                                                    hint_text: "Unit Value Input"
                                                    helper_text: "Text is always here"
                                                    helper_text_mode: "persistent"
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Quartile_TextFieldVal_One
                                                    hint_text: "Quarter #1 Value"
                                                    helper_text: "Quarter What Usage????????"
                                                    helper_text_mode: 'on_focus'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Quartile_TextFieldVal_Two
                                                    hint_text: "Quarter #2 Value"
                                                    helper_text: "Quarter What Usage????????"
                                                    helper_text_mode: 'on_focus'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Quartile_TextFieldVal_Three
                                                    hint_text: "Quarter #3 Value"
                                                    helper_text: "Quarter What Usage????????"
                                                    helper_text_mode: 'on_focus'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: Quartile_TextFieldVal_Four
                                                    hint_text: "Quarter #4 Value"
                                                    helper_text: "Quarter What Usage????????"
                                                    helper_text_mode: 'on_focus'
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Increment"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Decrement"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                            MDTextField:
                                                id: Total_ComputedVal
                                                hint_text: "Total Value"
                                                helper_text: "This value is automatically computed based from data..."
                                                helper_text_mode: "persistent"
                                                write_tab: False
                                                disabled: True
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                MDRaisedButton:
                                                    text: "Apply Changes"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.MDWorksheetWorker_DataEditor_Apply()
                                                MDFlatButton:
                                                    text: "Clear Input"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.MDWorksheetWorker_DataEditor_CleanInput()
                                                MDFlatButton:
                                                    text: "Undo Changes"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.MDWorksheetWorker_DataEditor_Undo()
                                    MDCard:
                                        size: dp(320), dp(190)
                                        size_hint_y: None
                                        padding: dp(15)
                                        AnchorLayout:
                                            anchor_x: 'left'
                                            anchor_y: 'top'
                                            BoxLayout:
                                                orientation:'vertical'
                                                size_hint_y: None
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "File Options"
                                                    width: dp(20)
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                StackLayout:
                                                    spacing: dp(10)
                                                    MDRaisedButton:
                                                        id: FileOpt_Save
                                                        text: "Save on Import Path"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                        on_release: app.ExcelFile_SaveOnCurrentPath()
                                                    MDRaisedButton:
                                                        id: FileOpt_Save
                                                        text: "Save on Export Path"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                        on_release: app.ExcelFile_SaveOnExportPath()
                                                    MDRaisedButton:
                                                        id: FileOpt_ReloadDataFile
                                                        text: "Load or Reload Data"
                                                        size_hint: None, None
                                                        size: 3 * dp(48), dp(48)
                                                        on_release: app.ExcelLoadInit_Prototype()
                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_2'
                        text: "Data Status Report"
                        icon: 'book-open'
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint_y: None
                            padding: dp(48)
                            spacing: 10
                            #1 Summation of Units, Show Proposed  and OnHand and OnStorage
                            #2 Most Used Item Recorded
                            #3 Due Dates
                            #4 Recently Added 
                        ScrollView:
                            do_scroll_x: False                              
                            GridLayout:
                                cols:2
                                size_hint_y: None
                                spacing: dp(10)
                                padding: dp(20)
                                height: self.minimum_height
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    BoxLayout:
                                        orientation:'vertical'
                                        spacing: dp(2)
                                        MDLabel:
                                            font_style: 'Headline'
                                            theme_text_color: 'Primary'
                                            text: "Total Units"
                                            text_size: self.size
                                            halign: 'left'
                                            valign: 'top'
                                        MDLabel:
                                            theme_text_color: 'Primary'
                                            font_style: "Display3"
                                            text_size: self.size
                                            text: '123901'
                                            halign: 'center'
                                            valign: 'center'

                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Total Proposed"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Overall'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Total OnHand Value"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Overall'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "On Storage Val"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Overall'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Most Used Item Recorded"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Overall'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Due Note Dates Added"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Not sure about this one...'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Recently Added Particular"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Not sure about this one...'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                MDCard:
                                    size: dp(320), dp(215)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Last Data Edited"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'Shows what data ppoint has been edited...'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size

                    MDBottomNavigationItem:
                        name: 'MainFrameWindow_3'
                        text: "Import Data / Export Pull Out"
                        icon: 'book-open'
                        ScrollView:
                            do_scroll_x: False                              
                            GridLayout:
                                cols:1
                                size_hint_y: None
                                spacing: dp(10)
                                padding: dp(20)
                                height: self.minimum_height
                                MDCard:

                                    size: dp(320), dp(285)
                                    size_hint_y: None
                                    padding: dp(15)
                                    
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Data Binding / Data Import"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'This is the part where things get started... Please set up and fill those text fields that is required in order to get go!'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: DataBind_FilePath
                                                    hint_text: "Excel File | Data Path"
                                                    required: True
                                                    helper_text: "Required, if you want to use this application!"
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                    text: 'C:\\Users\\janja\\Desktop\\sam.xlsx'
                                                MDTextField:
                                                    id: DataBind_FileArguments
                                                    hint_text: "Show True Value Instead of Formulae"
                                                    required: True
                                                    helper_text: "Optional, Leave it blank to save with formulae or else write True."
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Clear Path"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.IMD_EXPO_ButtonCallBackManager('ClearInput_Path')
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: DataBind_CellStartPoint
                                                    hint_text: "Cell Starting Point"
                                                    required: True
                                                    helper_text: "What cell do you want to get started reading?"
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                    text: 'B6'
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Clear Value"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.IMD_EXPO_ButtonCallBackManager('CallFunc_ClearStartPoint')
                                                MDTextField:
                                                    id: DataBind_CellEndPoint
                                                    hint_text: "Cell End Part Point"
                                                    required: True
                                                    helper_text: "What cell do you wish to stop at reading?"
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                    text: 'P25'
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Clear Value"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.IMD_EXPO_ButtonCallBackManager('CallFunc_ClearEndPoint')
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: DataBind_ExcelFileSheet
                                                    hint_text: "Sheet Name"
                                                    required: True
                                                    helper_text: "Required, this was added to know what sheet to use."
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                    text: 'Sheet1'
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Available Sheets"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    #on_release: app.IMD_EXPO_ButtonCallBackManager('ClearInput_ExcelFileSheet')
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Clear Path"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.IMD_EXPO_ButtonCallBackManager('ClearInput_ExcelFileSheet')
                                MDCard:
                                    size: dp(320), dp(165)
                                    size_hint_y: None
                                    padding: dp(15)
                                    StackLayout:
                                        spacing: dp(4)
                                        BoxLayout:
                                            orientation:'vertical'
                                            AnchorLayout:
                                                anchor_x:'left'
                                                anchor_y:'top'
                                                MDLabel:
                                                    font_style: 'Headline'
                                                    theme_text_color: 'Primary'
                                                    text: "Data Pull Out / Data Export"
                                                    text_size: self.size
                                                    halign: 'left'
                                                    valign: 'top'
                                                MDLabel:
                                                    text: 'This is the part that produces results! Please input the directory where you want to save.'
                                                    theme_text_color: 'Secondary'
                                                    font_style: "Body1"
                                                    text_size: self.size
                                            BoxLayout:
                                                orientation: 'horizontal'
                                                spacing: dp(10)
                                                padding: 0
                                                MDTextField:
                                                    id: DataBind_FileExportPath
                                                    hint_text: "Excel File | Data Path"
                                                    required: True
                                                    helper_text: "Required, if you want to export an Excel File!"
                                                    helper_text_mode: "on_focus"
                                                    write_tab: False
                                                    #on_dropfile: app._on_file_drop
                                                MDFlatButton:
                                                    theme_text_color: 'Custom'
                                                    text: "Clear Path"
                                                    size_hint: None, None
                                                    size: 3 * dp(48), dp(48)
                                                    on_release: app.IMD_EXPO_ButtonCallBackManager('CallFunc_ExportPathClear')
            Screen:
                name: 'MainWindow_AccountUserSelection'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: 0, dp(20)
                            StackLayout:
                                spacing:20
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: dp(20), 0
                                    spacing: 20
                                    MDLabel:
                                        text: 'Select an Registered Author'
                                        theme_text_color: 'Primary'
                                        font_style: "Headline"
                                        size_hint_y: None
                                        height: dp(15)
                                    MDLabel:
                                        text: 'Please choose your identity with your true identity!'
                                        theme_text_color: 'Secondary'
                                        font_style: "Body1"
                                        size_hint_y: None
                                        height: dp(3)
                                    ScrollView:
                                        do_scroll_x: False
                                        MDList:
                                            id: MDList_UserInsertion_Selection
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                            TwoLineAvatarListItem:
                                                type: "two-line"
                                                text: "Two-line item..."
                                                secondary_text: "with avatar"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
            Screen:
                name: 'MainWindow_AccountAddInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Add an Author'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'More staffs? Add more authors!'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    hint_text: "Input Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Input Your Password"
                                    required: True
                                    helper_text: "Password is needed to avoid changing authors without permission."
                                    helper_text_mode: "on_focus"
                                    password: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
            Screen:
                name: 'MainWindow_AccountDeleteInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: 0, dp(20)
                            StackLayout:
                                spacing:20
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: dp(20), 0
                                    spacing: 20
                                    MDLabel:
                                        text: 'Remove an Registered Author'
                                        theme_text_color: 'Primary'
                                        font_style: "Headline"
                                        size_hint_y: None
                                        height: dp(15)
                                    MDLabel:
                                        text: 'This is the place to remove an authors right of modification and view.'
                                        theme_text_color: 'Secondary'
                                        font_style: "Body1"
                                        size_hint_y: None
                                        height: dp(3)
                                    ScrollView:
                                        do_scroll_x: False
                                        MDList:
                                            id: MDList_UserDeletion_Selection
                                            NavigationDrawerIconButton:
                                                icon: 'tab-unselected'
                                                text: "Unselect Checked Author"
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                            TwoLineAvatarIconListItem:
                                                text: "Persons Name"
                                                secondary_text: "<Position>"
                                                AvatarSampleWidget:
                                                    source: './assets/avatar.png'
                                                IconRightSampleWidget:
                                    MDFlatButton:
                                        theme_text_color: 'Custom'
                                        text: "Remove Selected"
                                        size_hint: None, None
                                        size: 3 * dp(48), dp(48)
                                        pos_hint: {'center_y': 0.9}
            Screen:
                name: 'MainWindow_AccountEditInfo'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    Image:
                        source: 'assets/LayerTriangleVector3.jpg'
                        size_hint: None, None
                        size: 1920, 1080
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'center'
                    MDCard:
                        size_hint: None, None
                        size: dp(560), dp(470)
                        BoxLayout:
                            orientation: 'vertical'
                            padding: dp(20)
                            StackLayout:
                                spacing:20
                                MDLabel:
                                    text: 'Edit your Information'
                                    theme_text_color: 'Primary'
                                    font_style: "Headline"
                                    size_hint_y: None
                                    height: dp(15)
                                MDLabel:
                                    text: 'Type Mistake? Wrong Info? Correct That One Here!'
                                    theme_text_color: 'Secondary'
                                    font_style: "Body1"
                                    size_hint_y: None
                                    height: dp(3)
                                MDTextField:
                                    hint_text: "Edit Your First Name"
                                    required: True
                                    helper_text: "First Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Last Name"
                                    required: True
                                    helper_text: "Last Name Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Job Position"
                                    required: True
                                    helper_text: "Job Position Needed for Author Assignment"
                                    helper_text_mode: "on_focus"
                                    write_tab: False
                                MDTextField:
                                    hint_text: "Edit Your Password"
                                    required: True
                                    helper_text: "Password is needed but it is required when the program version is not individual use."
                                    helper_text_mode: "persistent"
                                    password: True
                                    disabled: True
                                    write_tab: False
                                MDLabel:
                                    text: 'Want to use the program with modifying features? Click Admin Previledge for more info.'
                                    theme_text_color: 'Secondary'
                                    font_style: "Caption"
                                    size_hint_y: None
                                    height: dp(8)
                                MDFlatButton:
                                    theme_text_color: 'Custom'
                                    text: "Admin Previledge"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)
                                    disabled: True
                                MDRaisedButton:
                                    text: "Submit Data"
                                    size_hint: None, None
                                    size: 3 * dp(48), dp(48)